In [1]:
# Prepare your workstation.
import pandas as pd

# Read CSV file from the current working directory.
fitness = pd.read_csv('daily_activity.csv')

print(fitness.shape)

# Descriptive statistics.
fitness.describe()

(940, 15)

,Id,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
count,9.400000e+02,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000,940.000000
mean,4.855407e+09,7637.910638,5.489702,5.475351,0.108171,1.502681,0.567543,3.340819,0.001606,21.164894,13.564894,192.812766,991.210638,2303.609574
std,2.424805e+09,5087.150742,3.924606,3.907276,0.619897,2.658941,0.883580,2.040655,0.007346,32.844803,19.987404,109.174700,301.267437,718.166862
min,1.503960e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.320127e+09,3789.750000,2.620000,2.620000,0.000000,0.000000,0.000000,1.945000,0.000000,0.000000,0.000000,127.000000,729.750000,1828.500000
50%,4.445115e+09,7405.500000,5.245000,5.245000,0.000000,0.210000,0.240000,3.365000,0.000000,4.000000,6.000000,199.000000,1057.500000,2134.000000
75%,6.962181e+09,10727.000000,7.712500,7.710000,0.000000,2.052500,0.800000,4.782500,0.000000,32.000000,19.000000,264.000000,1229.500000,2793.250000
max,8.877689e+09,36019.000000,28.030001,28.030001,4.942142,21.920000,6.480000,10.710000,0.110000,210.000000,143.000000,518.000000,1440.000000,4900.000000

In [5]:
# max = Returns max of a column
print(fitness['TotalDistance'].max())

# min = Returns min of a column
print(fitness['TotalDistance'].min())

# sum = Returns sum of a column 
print(fitness['TotalDistance'].sum())

28.0300006866455
0.0
5160.31999460049

In [7]:
q1 = fitness['TotalSteps'].quantile(0.25)
q3 = fitness['TotalSteps'].quantile(0.75)

iqr_TotalSteps = q3 - q1

print(q1)
print(q3)
iqr_TotalSteps

3789.75
10727.0

6937.25

In [8]:
# Variance of the DataFrame.
print(fitness.var())

# Variance of total distance.
print(fitness['TotalDistance'].var())

Id                          5.879682e+18
TotalSteps                  2.587910e+07
TotalDistance               1.540253e+01
TrackerDistance             1.526681e+01
LoggedActivitiesDistance    3.842717e-01
VeryActiveDistance          7.069968e+00
ModeratelyActiveDistance    7.807142e-01
LightActiveDistance         4.164274e+00
SedentaryActiveDistance     5.396631e-05
VeryActiveMinutes           1.078781e+03
FairlyActiveMinutes         3.994963e+02
LightlyActiveMinutes        1.191912e+04
SedentaryMinutes            9.076207e+04
Calories                    5.157636e+05
dtype: float64
15.40253153801325

/var/folders/2y/jw_fvb1s0nncctnyn9dc159w0000gn/T/ipykernel_61667/173285678.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(fitness.var())